# Change the prefix key to Ctrl-a
set -g prefix C-a

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Dissolve Ctrl-b key bind
unbind C-b

# Enable mouse control
set -g mouse on

# Reduce delay time after escape key
set -sg escape-time 1

# Reload setting file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Create a new window in the current directory
bind c new-window -c "#{pane_current_path}"

# Split the pane vertically by |
bind | split-window -h -c "#{pane_current_path}"

# Split the pane horizontally by -
bind - split-window -v -c "#{pane_current_path}"

# Move the pane with Vim's key binding
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize the pane with Vim's key binding
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Specify terminal type
set -g default-terminal "xterm-256color"

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Toggle panes synchronizing
bind S set-window-option synchronize-panes

